# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/srchTypeErr.yaml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseSrchtypeerr(HttpRunner):

    config = Config("PhoneSearch").base_url("${ENV(BASEURL)}")

    teststeps = [
        Step(
            RunRequest("searchByidAndName")
            .with_variables(**{"a": None, "b": "Cresh"})
            .get("/searchPhone")
            .with_headers(**{"UContent-Type": "application/json"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.Error_code", 11)
        ),
    ]


if __name__ == "__main__":
    TestCaseSrchtypeerr().test_start()
