# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/srchNameAndId.yaml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseSrchnameandid(HttpRunner):

    config = Config("PhoneSearch").base_url("${ENV(BASEURL)}")

    teststeps = [
        Step(
            RunRequest("searchByidAndName")
            .with_variables(**{"a": 3, "b": "Ami"})
            .get("/searchPhone")
            .with_headers(**{"UContent-Type": "application/json"})
            .with_json({"a": "$a", "b": "$b"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.reference", 18900001236)
            .assert_equal("body.error_message", "success")
            .assert_equal("body.Error_code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseSrchnameandid().test_start()
